package com.pjariwala.enums;

public enum ActionType {
  LOGIN,
  LOGOUT,
  CREATE_STUDENT,
  UPDATE_STUDENT,
  DELETE_STUDENT,
  CREATE_BATCH,
  UPDATE_BATCH,
  DELETE_BATCH,
  CREATE_SESSION,
  UPDATE_SESSION,
  DELETE_SESSION,
  MARK_ATTENDANCE,
  ENROLL_STUDENT,
  UPDATE_ENROLLMENT,
  REMOVE_ENROLLMENT,
  PAYMENT_RECEIVED,
  PAYMENT_UPDATED,
  PROFILE_UPDATE,
  PASSWORD_CHANGE,
  BULK_ENROLLMENT,
  BULK_OPERATION,
  VIEW_DASHBOARD,
  VIEW_REPORTS,
  SYSTEM_ACTION
}
